<?php

/**
 * Harvv Laravel Pixel — configuration defaults.
 *
 * These defaults are merged in by the service provider, so the package
 * works without `php artisan vendor:publish`. Publish only when you need
 * to customize beyond what env vars cover.
 *
 * Most installations only need:
 *   HARVV_SITE_KEY=<your site key from harvv.com/site/<id>/settings/install>
 *
 * Everything else has a sensible default.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Site key
    |--------------------------------------------------------------------------
    | Your site's pixel key from harvv.com. The package is a complete no-op
    | when this is empty — safe to ship code with the package installed but
    | unconfigured (e.g., on a fresh staging deploy).
    */

    'site_key' => env('HARVV_SITE_KEY'),

    /*
    |--------------------------------------------------------------------------
    | Enabled
    |--------------------------------------------------------------------------
    | Global on/off switch. Defaults to enabled in production + staging,
    | disabled in 'local' and 'testing' so dev events don't pollute prod
    | analytics. Override with HARVV_ENABLED=true|false to be explicit.
    */

    'enabled' => env(
        'HARVV_ENABLED',
        ! in_array(env('APP_ENV', 'production'), ['local', 'testing'], true)
    ),

    /*
    |--------------------------------------------------------------------------
    | Pixel host
    |--------------------------------------------------------------------------
    | The Harvv receiver URL. Don't change unless you're running an on-prem
    | Harvv install — the default is the only one anyone normally needs.
    */

    'host' => env('HARVV_HOST', 'https://harvv.com'),

    /*
    |--------------------------------------------------------------------------
    | Server-side context
    |--------------------------------------------------------------------------
    | When the HarvvContext middleware is registered, the package POSTs a
    | small server-side context payload (route name, hashed user id, request
    | id) to /v1/context so the Harvv dashboard can show "rage click on
    | checkout.show, user 12345, on third attempt" instead of just
    | "rage click on /checkout".
    |
    | The middleware is OPT-IN. Adding it is a one-line change that the
    | install command offers to make for you.
    */

    'context' => [

        'enabled' => env('HARVV_CONTEXT_ENABLED', true),

        /*
        | hash_user_ids — TRUE by default.
        |
        | SECURITY: When true (default), user IDs are hashed with
        | sha256(user_id . site_key) before being sent. We can match issues
        | to specific users in your dashboard without ever seeing your
        | primary keys.
        |
        | Set HARVV_CONTEXT_UNHASHED=true to send plaintext user IDs. This
        | is RARELY what you want — it exposes your user PKs to the Harvv
        | pipeline. `php artisan harvv:install` will print a red warning
        | when it detects this flag.
        */
        'hash_user_ids' => env('HARVV_CONTEXT_UNHASHED', false) ? false : true,

        /*
        | HMAC secret for signing context payloads. The Harvv receiver
        | verifies every server-side POST with this. Generated by
        | `php artisan harvv:install`. Without it, the middleware no-ops
        | gracefully — the pixel itself still works.
        */
        'hmac_secret' => env('HARVV_HMAC_SECRET'),

        /*
        | Routes the context middleware skips entirely. These match Laravel
        | route patterns (segments separated by /). Admin / debug / internal
        | tooling routes default to excluded so you never accidentally ship
        | admin user IDs to your analytics pipeline.
        */
        'excluded_routes' => [
            'admin/*',
            'horizon/*',
            'telescope/*',
            'pulse/*',
            'nova/*',
            'filament/*',
            'livewire/*',         // Livewire's internal XHR — pixel handles UI updates client-side
            'health',
            '_debugbar/*',
            'sanctum/csrf-cookie',
        ],

        /*
        | Whether to include the route NAME (e.g., 'checkout.show') in the
        | context payload. Disable if your route names contain sensitive
        | tokens; the URL path still goes through.
        */
        'include_route_name' => env('HARVV_CONTEXT_ROUTE_NAME', true),

        /*
        | Whether to include the authenticated user ID. Hashed unless
        | HARVV_CONTEXT_UNHASHED is set. Disable if your auth model exposes
        | data you'd rather not correlate.
        */
        'include_user_id' => env('HARVV_CONTEXT_USER_ID', true),

        /*
        | Auth guard to read for user_id. Defaults to Laravel's default
        | guard. Change to 'api' / 'sanctum' / custom guard if your app
        | uses something other than web.
        */
        'auth_guard' => env('HARVV_CONTEXT_GUARD', null),
    ],

    /*
    |--------------------------------------------------------------------------
    | Logging
    |--------------------------------------------------------------------------
    | The package writes its own diagnostic logs to Laravel's logger. Use
    | the default channel, or set a dedicated channel for isolation.
    | Useful when you want to filter Harvv's chatter out of your main log
    | stream (e.g., a tail -f stack channel).
    */

    'log_channel' => env('HARVV_LOG_CHANNEL', null),

];
